services:
  zeal8bit-dev-env:
    container_name: zeal8bit
    platform: linux/amd64
    privileged: true
    image: ${ZDE_IMAGE:-zoul0813/zeal-dev-environment}:${ZDE_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ${PWD}:/src
      - ./home:/home/zeal8bit
      - ./mnt:/mnt
      - ./etc/supervisor.d:/etc/supervisor.d
    ports:
      - 1145:1145
      - 1155:1155
    command: ["sleep","infinity"]
