services:
  zeal8bit-dev-env:
    container_name: zeal8bit
    privileged: true
    image: ${ZDE_IMAGE:-zoul0813/zeal-dev-environment}:${ZDE_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    restart: on-failure
    volumes:
      - ${PWD}:/src
      - ./home:/home/zeal8bit
    ports:
      - 1145:1145
    command: ["sleep","infinity"]
