services:
  zeal8bit-dev-env:
    container_name: zeal8bit
    platform: linux/amd64
    privileged: true
    image: ${ZDE_IMAGE:-zoul0813/zeal-dev-environment}:${ZDE_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    restart: on-failure
    environment:
      ZDE: true
      ZOS_PATH: /home/zeal8bit/Zeal-8-bit-OS
      ZVB_SDK_PATH: /home/zeal8bit/Zeal-VideoBoard-SDK
      ZGDK_PATH: /home/zeal8bit/zeal-game-dev-kit
      SDCC_PATH: /opt/sdcc
      PYTHON_BIN: /opt/penv/bin
      ZAR_PATH: /home/zeal8bit/zeal-archiver
    volumes:
      - ${PWD}:/src
      - ./home:/home/zeal8bit
      - ./mnt:/mnt
    ports:
      - 1145:1145
    command: ["sleep","infinity"]
