#!/bin/bash

set +x

ZDE_PATH=$(dirname "$0")
mkdir -p ~/.zde

ZDE_MOUNTED=
if [ -f ~/.zde/mount ]; then
  ZDE_MOUNTED=$(cat ~/.zde/mount)
fi

COMMAND=$1
shift

RUNNING="1"
CONTAINER_CMD="${ZDE_USE:-default}"
CONTAINER_NAME=zeal8bit
COMPOSE_PATH="$ZDE_PATH/docker-compose.yml"
export ZDE_IMAGE=zoul0813/zeal-dev-environment
export ZDE_VERSION="${ZDE_VERSION:=latest}"
# export ZDE_PLATFORM=linux/amd64
if ([ "$CONTAINER_CMD" = "default" ] || [ "$CONTAINER_CMD" = "docker" ]) && command -v docker 2>&1 >/dev/null; then
  CONTAINER_CMD=docker
  $CONTAINER_CMD ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"
  RUNNING=$?
elif ([ "$CONTAINER_CMD" = "default" ] || [ "$CONTAINER_CMD" = "podman" ]) && command -v podman 2>&1 >/dev/null; then
  CONTAINER_CMD=podman
  $CONTAINER_CMD ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"
  RUNNING=$?
else
  echo "WARNING: docker/podman not found, ensure docker, or podman, is installed before using ZDE"
fi

emulator()
{
  CMD=$1
  case $CMD in
    start)
      shift
      emulator_start $@
      ;;
    stop)
      shift
      emulator_stop
      ;;
    *)
      emulator_start $@
      ;;
  esac
}

emulator_start()
{
  # supervisord -c /etc/supervisord.conf
  $CONTAINER_CMD exec -t zeal8bit supervisorctl status emulator
  STATUS=$?
  if [ "$STATUS" = "3" ]; then
    $CONTAINER_CMD exec -t zeal8bit supervisorctl start emulator
  fi
  PATH=$PATH:"$ZDE_PATH"/bin "$ZDE_PATH"/bin/xdg-open "http://127.0.0.1:1145/?r=latest&$1"
}

emulator_stop()
{
  $CONTAINER_CMD exec -t zeal8bit supervisorctl status emulator
  STATUS=$?
  if [ "$STATUS" = "0" ]; then
    $CONTAINER_CMD exec -t zeal8bit supervisorctl stop emulator
  fi
}

stop()
{
  if [ "$RUNNING" = "0" ]; then
    $CONTAINER_CMD compose -f "$COMPOSE_PATH" stop
    rm ~/.zde/mount
    RUNNING="1"
  else
    echo "ZDE is not running"
  fi
}

start()
{
  if [ "$RUNNING" = "1" ]; then
    $CONTAINER_CMD compose -f "$COMPOSE_PATH" up -d
    echo $PWD > ~/.zde/mount
    RUNNING="0"
  else
    echo "ZDE is already running"
  fi
}

make_image()
{
  TYPE=$1
  SIZE=$2

  if [ -f "$ZDE_PATH/mnt/$TYPE.img" ]; then
    read -p "Image exists, overwrite? ([Y]es, [N]o)" -n 1 -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
    fi

    rm "$ZDE_PATH/mnt/$TYPE.img"
  fi

  shift
  case $TYPE in
    eeprom)
      $CONTAINER_CMD exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh eeprom ${SIZE:=32}
      ;;
    cf)
      $CONTAINER_CMD exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh cf ${SIZE:=64}
      ;;
    sd)
      $CONTAINER_CMD exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh sd ${SIZE:=64}
      ;;
    *)
      echo "Invalid arguments, must provide TYPE (eeprom, cf, sd)"
      ;;
  esac
}

case $COMMAND in
  update)
    RESTART=$RUNNING
    if [ "$RUNNING" = "0" ]; then
      stop
    fi
    echo "Pulling latest Zeal 8-bit repositories"
    git -C "$ZDE_PATH" checkout main
    git -C "$ZDE_PATH" submodule init
    git -C "$ZDE_PATH" pull --recurse-submodules origin main
    $CONTAINER_CMD image pull ${ZDE_IMAGE}:${ZDE_VERSION}
    if [ "$RESTART" = "0" ]; then
      start
    fi
    ;;
  status)
    echo -n "ZDE is "
    if [ "$RUNNING" = "1" ]; then
      echo "stopped"
    else
      echo -n "running, mounted to ${ZDE_MOUNTED}"
    fi
    echo " with ${CONTAINER_CMD}"
    ;;
  start)
    start $@
    ;;
  stop)
    stop $@
    ;;
  restart)
    stop
    start $@
    ;;
  emu)
    emulator $@
    ;;
  emulator)
    emulator $@
    ;;
  make)
    if [[ ! -z "${ASEPRITE_PATH}" ]]; then
      make -f "$ZDE_PATH/home/zeal-game-dev-kit/aseprite.mk"
    fi
    if [ "$RUNNING" = "0" ]; then
      $CONTAINER_CMD exec --env-file="$ZDE_PATH/.env" -t $CONTAINER_NAME make $@
    else
      echo "ZDE is not running"
    fi
    ;;
  create)
    $CONTAINER_CMD run --rm -v $(pwd):/tmp -v $ZDE_PATH/home:/home/zeal8bit --env-file=$ZDE_PATH/.env $ZDE_IMAGE:$ZDE_VERSION /home/zeal8bit/templates/create.sh "$@"
    ;;
  image)
    make_image $@
    ;;
  rebuild)
    if [ "$RUNNING" = "0" ]; then
      $CONTAINER_CMD compose -f "$COMPOSE_PATH" down
    fi
    $CONTAINER_CMD compose -f "$COMPOSE_PATH" build
    ;;
  *)
    echo "Help: update, status, start, stop, make, emu[lator], create, image"
    ;;
esac
