#!/bin/sh

set +x

ZDE_PATH=$(dirname $0)
mkdir -p ~/.zde

ZDE_MOUNTED=
if [ -f ~/.zde/mount ]; then
  ZDE_MOUNTED=$(cat ~/.zde/mount)
fi

COMMAND=$1
shift

RUNNING="1"
CONTAINER_NAME=zeal8bit
COMPOSE_PATH=$ZDE_PATH/docker-compose.yml
export ZDE_IMAGE=zoul0813/zeal-dev-environment
export ZDE_VERSION="${ZDE_VERSION:=latest}"
if command -v docker 2>&1 >/dev/null; then
  docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"
  RUNNING=$?
else
  echo "WARNING: docker not found, ensure docker is installed before using ZDE"
fi

emulator()
{
  CMD=$1
  case $CMD in
    start)
      shift
      emulator_start $@
      ;;
    stop)
      shift
      emulator_stop
      ;;
    *)
      emulator_start $@
      ;;
  esac
}

emulator_start()
{
  # supervisord -c /etc/supervisord.conf
  docker exec -t zeal8bit supervisorctl status emulator
  STATUS=$?
  if [ "$STATUS" = "3" ]; then
    docker exec -t zeal8bit supervisorctl start emulator
  fi
  PATH=$PATH:$ZDE_PATH/bin $ZDE_PATH/bin/xdg-open "http://127.0.0.1:1145/?r=latest&$1"
}

emulator_stop()
{
  docker exec -t zeal8bit supervisorctl status emulator
  STATUS=$?
  if [ "$STATUS" = "0" ]; then
    docker exec -t zeal8bit supervisorctl stop emulator
  fi
}

stop()
{
  if [ "$RUNNING" = "0" ]; then
    docker compose -f ${COMPOSE_PATH} stop
    rm ~/.zde/mount
    RUNNING="1"
  else
    echo "ZDE is not running"
  fi
}

start()
{
  if [ "$RUNNING" = "1" ]; then
    docker compose -f ${COMPOSE_PATH} up -d
    echo $PWD > ~/.zde/mount
    RUNNING="0"
  else
    echo "ZDE is already running"
  fi
}

case $COMMAND in
  update)
    RESTART=$RUNNING
    if [ "$RUNNING" = "0" ]; then
      stop
    fi
    echo "Pulling latest Zeal 8-bit repositories"
    git -C $ZDE_PATH checkout main
    git -C $ZDE_PATH fetch
    git -C $ZDE_PATH pull origin main
    git -C $ZDE_PATH submodule update --init --recursive --remote
    docker image pull ${ZDE_IMAGE}:${ZDE_VERSION}
    if [ "$RESTART" = "0" ]; then
      start
    fi
    ;;
  status)
    if [ "$RUNNING" = "1" ]; then
      echo "ZDE is stopped"
    else
      echo "ZDE is running, mounted to ${ZDE_MOUNTED}"
    fi
    ;;
  start)
    start $@
    ;;
  stop)
    stop $@
    ;;
  restart)
    stop
    start $@
    ;;
  emu)
    emulator $@
    ;;
  emulator)
    emulator $@
    ;;
  make)
    if [ "$RUNNING" = "0" ]; then
      docker exec -t $CONTAINER_NAME make $@
    else
      echo "ZDE is not running"
    fi
    ;;
  rebuild)
    if [ "$RUNNING" = "0" ]; then
      docker compose -f ${COMPOSE_PATH} down
    fi
    docker compose -f ${COMPOSE_PATH} build
    ;;
  *)
    echo "Help: update, status, start, stop, make"
    ;;
esac